<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class CardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cards')->insert([
            //Subject 1: Trường học
            [
                'subject_id' => 1,
                'front' => '<p>học viện</p>',
                'back' => '<p>academy</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>cao đẳng</p>',
                'back' => '<p>college</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>trung học phổ thông</p>',
                'back' => '<p>high school</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>trường quốc tế</p>',
                'back' => '<p>international</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>trường mẫu giáo</p>',
                'back' => '<p>kindergarten</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>trường tiểu học</p>',
                'back' => '<p>primary school</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>trường tư thục</p>',
                'back' => '<p>private school</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>trường công</p>',
                'back' => '<p>public school</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>trung học phổ thông</p>',
                'back' => '<p>secondary school</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>đại học</p>',
                'back' => '<p>university</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>bảng viết</p>',
                'back' => '<p>board</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>sách</p>',
                'back' => '<p>book</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>lớp học</p>',
                'back' => '<p>classroom</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>thư viện</p>',
                'back' => '<p>library</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>tủ đồ</p>',
                'back' => '<p>locker</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>sân chơi</p>',
                'back' => '<p>playground</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => '<p>sân trường</p>',
                'back' => '<p>schoolyard</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],

            //subject 2: Nghề nghiệp
            [
                'subject_id' => 2,
                'front' => '<p>vệ sĩ</p>',
                'back' => '<p>bodyguard</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>thẩm phán</p>',
                'back' => '<p>judge</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>luật sư</p>',
                'back' => '<p>lawyer</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>barrister</p>',
                'back' => '<p>luật sư bào chữ</p>a',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>thám tử</p>',
                'back' => '<p>detective</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>lập trình viên</p>',
                'back' => '<p>programmer</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>phát triển phần mềm</p>',
                'back' => '<p>software developer</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>kế toán</p>',
                'back' => '<p>accountant</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>doanh nhân</p>',
                'back' => '<p>businessman</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>cố vấn tài chính</p>',
                'back' => '<p>financial adviser</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>bác sĩ</p>',
                'back' => '<p>doctor</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>y tá</p>',
                'back' => '<p>nurse</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>thợ làm bánh</p>',
                'back' => '<p>baker</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>thu ngân</p>',
                'back' => '<p>cashier</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>người trồng hoa</p>',
                'back' => '<p>florist</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>lao công</p>',
                'back' => '<p>cleaner</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>thợ điện</p>',
                'back' => '<p>electrician</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>thợ mộc</p>',
                'back' => '<p>carpenter</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>người làm vườn</p>',
                'back' => '<p>gardener</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => '<p>thợ sửa ống nước</p>',
                'back' => '<p>plumber</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],

            //subject 3: thể thao
            [
                'subject_id' => 3,
                'front' => '<p>bóng đá</p>',
                'back' => '<p>football</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>bóng chuyền</p>',
                'back' => '<p>volleyball</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>bóng giổ</p>',
                'back' => '<p>basketball</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>cầu lông</p>',
                'back' => '<p>badminton</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>câu cá</p>',
                'back' => '<p>fishing</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>bơi lội</p>',
                'back' => '<p>swimming</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>lặn</p>',
                'back' => '<p>scuba div</p>ing',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>bi-a</p>',
                'back' => '<p>snooker</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>điền kinh</p>',
                'back' => '<p>athletics</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>chạy bộ</p>',
                'back' => '<p>running</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>quần vợt</p>',
                'back' => '<p>teninis</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>bóng bàn</p>',
                'back' => '<p>table tennis</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>trượt tuyết</p>',
                'back' => '<p>skiing</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>trượt ván</p>',
                'back' => '<p>skateboarding</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>lướt sóng</p>',
                'back' => '<p>surfing</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>leo núi</p>',
                'back' => '<p>climbing</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>match</p>',
                'back' => '<p>trận đấu</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>cuộc thi đấu</p>',
                'back' => '<p>competition</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>khán đài</p>',
                'back' => '<p>stand</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>trọng tài</p>',
                'back' => '<p>umpire</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>khán giả</p>',
                'back' => '<p>spectator</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => '<p>tỉ số</p>',
                'back' => '<p>score</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],


            //subject 4: Thành phố
            [
                'subject_id' => 4,
                'front' => '<p>thành phố</p>',
                'back' => '<p>city</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>vỉa hè</p>',
                'back' => '<p>sidewalk</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>giao lộ</p>',
                'back' => '<p>intersection</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>đại lộ</p>',
                'back' => '<p>avenue</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>vòng xuyến</p>',
                'back' => '<p>roundabout</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>chung cư</p>',
                'back' => '<p>apartment hous</p>e',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>trung tâm thành phố</p>',
                'back' => '<p>downtown</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>trung tâm thương mại</p>',
                'back' => '<p>shopping mall</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>khu công nghiệp</p>',
                'back' => '<p>industrial zone</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>khu dân cư</p>',
                'back' => '<p>residential area</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>quảng trường</p>',
                'back' => '<p>square</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>tiện nghi</p>',
                'back' => '<p>amenities</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>hối hả</p>',
                'back' => '<p>hustle</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>cuộc sống về đêm</p>',
                'back' => '<p>nightlife</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>sôi động</p>',
                'back' => '<p>vibrant</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>ùn tắc giao thông</p>',
                'back' => '<p>traffic jam</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>ô nhiễm</p>',
                'back' => '<p>pollution</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>overload</p>',
                'back' => '<p>quá tải</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => '<p>cám dỗ</p>',
                'back' => '<p>lure</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],

            //subject 5: cảm xúc
            [
                'subject_id' => 5,
                'front' => '<p>Phấn khích</p>',
                'back' => '<p>excited</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>vui vẻ</p>',
                'back' => '<p>amused</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>vô cùng hạnh phúc</p>',
                'back' => '<p>ecstatic</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>rất hạnh phúc</p>',
                'back' => '<p>delighted</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>tự tin</p>',
                'back' => '<p>confident</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>ngạc nhiên</p>',
                'back' => '<p>surprised</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>nhiệt tình</p>',
                'back' => '<p>enthusiastic</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>tuyệt vời</p>',
                'back' => '<p>great</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>lạc quan</p>',
                'back' => '<p>positive</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>thư giãn</p>',
                'back' => '<p>relaxed</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>tuyệt vời</p>',
                'back' => '<p>wonderful</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>tuyệt vời</p>',
                'back' => '<p>terrific</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>buồn</p>',
                'back' => '<p>sad</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>sợ hãi</p>',
                'back' => '<p>angry</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>lo lắng</p>',
                'back' => '<p>anxious</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>sợ hãi</p>',
                'back' => '<p>horrified</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>hơi lo lắng</p>',
                'back' => '<p>apprehensive</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>kiêu ngạo</p>',
                'back' => '<p>arrogant</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => '<p>miễn cưỡng</p>',
                'back' => '<p>reluctant</p>',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
        ]);
    }
}
