<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class CardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cards')->insert([
            //Subject 1: Trường học
            [
                'subject_id' => 1,
                'front' => 'học viện',
                'back' => 'academy',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'cao đẳng',
                'back' => 'college',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'trung học phổ thông',
                'back' => 'high school',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'trường quốc tế',
                'back' => 'international',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'trường mẫu giáo',
                'back' => 'kindergarten',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'trường tiểu học',
                'back' => 'primary school',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'trường tư thục',
                'back' => 'private school',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'trường công',
                'back' => 'public school',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'trung học phổ thông',
                'back' => 'secondary school',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'đại học',
                'back' => 'university',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'bảng viết',
                'back' => 'board',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'sách',
                'back' => 'book',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'lớp học',
                'back' => 'classroom',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'thư viện',
                'back' => 'library',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'tủ đồ',
                'back' => 'locker',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'sân chơi',
                'back' => 'playground',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 1,
                'front' => 'sân trường',
                'back' => 'schoolyard',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],

            //subject 2: Nghề nghiệp
            [
                'subject_id' => 2,
                'front' => 'vệ sĩ',
                'back' => 'bodyguard',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'thẩm phán',
                'back' => 'judge',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'luật sư',
                'back' => 'lawyer',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'barrister',
                'back' => 'luật sư bào chữa',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'thám tử',
                'back' => 'detective',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'lập trình viên',
                'back' => 'programmer',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'phát triển phần mềm',
                'back' => 'software developer',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'kế toán',
                'back' => 'accountant',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'doanh nhân',
                'back' => 'businessman',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'cố vấn tài chính',
                'back' => 'financial adviser',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'bác sĩ',
                'back' => 'doctor',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'y tá',
                'back' => 'nurse',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'thợ làm bánh',
                'back' => 'baker',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'thu ngân',
                'back' => 'cashier',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'người trồng hoa',
                'back' => 'florist',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'lao công',
                'back' => 'cleaner',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'thợ điện',
                'back' => 'electrician',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'thợ mộc',
                'back' => 'carpenter',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'người làm vườn',
                'back' => 'gardener',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 2,
                'front' => 'thợ sửa ống nước',
                'back' => 'plumber',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],

            //subject 3: thể thao
            [
                'subject_id' => 3,
                'front' => 'bóng đá',
                'back' => 'football',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'bóng chuyền',
                'back' => 'volleyball',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'bóng giổ',
                'back' => 'basketball',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'cầu lông',
                'back' => 'badminton',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'câu cá',
                'back' => 'fishing',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'bơi lội',
                'back' => 'swimming',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'lặn',
                'back' => 'scuba diving',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'bi-a',
                'back' => 'snooker',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'điền kinh',
                'back' => 'athletics',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'chạy bộ',
                'back' => 'running',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'quần vợt',
                'back' => 'teninis',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'bóng bàn',
                'back' => 'table tennis',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'trượt tuyết',
                'back' => 'skiing',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'trượt ván',
                'back' => 'skateboarding',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'lướt sóng',
                'back' => 'surfing',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'leo núi',
                'back' => 'climbing',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'match',
                'back' => 'trận đấu',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'cuộc thi đấu',
                'back' => 'competition',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'khán đài',
                'back' => 'stand',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'trọng tài',
                'back' => 'umpire',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'khán giả',
                'back' => 'spectator',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 3,
                'front' => 'tỉ số',
                'back' => 'score',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],


            //subject 4: Thành phố
            [
                'subject_id' => 4,
                'front' => 'thành phố',
                'back' => 'city',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'vỉa hè',
                'back' => 'sidewalk',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'giao lộ',
                'back' => 'intersection',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'đại lộ',
                'back' => 'avenue',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'vòng xuyến',
                'back' => 'roundabout',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'chung cư',
                'back' => 'apartment house',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'trung tâm thành phố',
                'back' => 'downtown',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'trung tâm thương mại',
                'back' => 'shopping mall',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'khu công nghiệp',
                'back' => 'industrial zone',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'khu dân cư',
                'back' => 'residential area',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'quảng trường',
                'back' => 'square',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'tiện nghi',
                'back' => 'amenities',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'hối hả',
                'back' => 'hustle',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'cuộc sống về đêm',
                'back' => 'nightlife',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'sôi động',
                'back' => 'vibrant',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'ùn tắc giao thông',
                'back' => 'traffic jam',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'ô nhiễm',
                'back' => 'pollution',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'overload',
                'back' => 'quá tải',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 4,
                'front' => 'cám dỗ',
                'back' => 'lure',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],

            //subject 5: cảm xúc
            [
                'subject_id' => 5,
                'front' => 'Phấn khích',
                'back' => 'excited',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'vui vẻ',
                'back' => 'amused',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'vô cùng hạnh phúc',
                'back' => 'ecstatic',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'rất hạnh phúc',
                'back' => 'delighted',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'tự tin',
                'back' => 'confident',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'ngạc nhiên',
                'back' => 'surprised',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'nhiệt tình',
                'back' => 'enthusiastic',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'tuyệt vời',
                'back' => 'great',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'lạc quan',
                'back' => 'positive',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'thư giãn',
                'back' => 'relaxed',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'tuyệt vời',
                'back' => 'wonderful',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'tuyệt vời',
                'back' => 'terrific',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'buồn',
                'back' => 'sad',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'sợ hãi',
                'back' => 'angry',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'lo lắng',
                'back' => 'anxious',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'sợ hãi',
                'back' => 'horrified',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'hơi lo lắng',
                'back' => 'apprehensive',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'kiêu ngạo',
                'back' => 'arrogant',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],
            [
                'subject_id' => 5,
                'front' => 'miễn cưỡng',
                'back' => 'reluctant',
                'num_of_study' => 0,
                'level_of_card' => 1,
                'expiry_date' => Carbon::now(),
            ],

        ]);
    }
}
